M48
; DRILL file {KiCad 7.0.6} date Sat Dec 30 20:12:12 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-30T20:12:12-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X7.3031Y-2.2244
X7.3031Y-2.4213
T2
X5.3506Y-3.9323
X5.4006Y-2.0323
X7.4006Y-2.6323
X7.4006Y-3.7323
T0
M30
